server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/Students?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: "123456"

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  h2:
    console:
      enabled: true
      path: /h2-console

app:
  jwtSecret:  myVerySecureSecretKeyForJWTTokenGeneration1234567890ABCDEFGH
  jwtExpirationMs: 86400000

logging:
  level:
    com.spectro.studentapi: DEBUG
    org.springframework.security: DEBUG
